export const AUTH_LOGGING_IN = '[AUTH] LOGGING_IN';
export const AUTH_LOGGED_IN = '[AUTH] LOGGED_IN';
export const AUTH_ERR_LOG_IN = '[AUTH] ERR_LOG_IN';
export const AUTH_LOGOUT = '[AUTH] LOGOUT';
export const AUTH_CLEAR_LOGIN_ERROR_MESSAGE = '[AUTH] CLEAR_LOGIN_ERROR_MESSAGE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const USER_UPDATE_LOADING ="USER_UPDATE_LOADING";
export const USER_UPDATE_SUCCESS ="USER_UPDATE_SUCCESS";
export const USER_UPDATE_ERROR ="USER_UPDATE_ERROR";
export const PASSWORD_UPDATE_LOADING="PASSWORD_UPDATE_LOADING";
export const PASSWORD_UPDATE_SUCCESS="PASSWORD_UPDATE_SUCCESS";
export const PASSWORD_UPDATE_ERROR="PASSWORD_UPDATE_ERROR";
////////////////////


export const PASSWORD_RESET_LOADING="PASSWORD_RESET_LOADING";
export const PASSWORD_RESET_SUCCESS="PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_ERROR="PASSWORD_RESET_ERROR";